/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElC: typeof import('element-plus/es')['ElC']
  const ElColl: typeof import('element-plus/es')['ElColl']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
