/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./src/components/base.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCo: typeof import('element-plus/es')['ElCo']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    'ElRadio-': typeof import('element-plus/es')['ElRadio-']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Question1: typeof import('./src/components/demo/question1.vue')['default']
    Question2: typeof import('./src/components/demo/question2.vue')['default']
    Question3: typeof import('./src/components/demo/question3.vue')['default']
    Question4: typeof import('./src/components/demo/question4.vue')['default']
    Question5: typeof import('./src/components/demo/question5.vue')['default']
    Question6: typeof import('./src/components/demo/question6.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowData: typeof import('./src/components/demo/showData.vue')['default']
    TypeIt: typeof import('./src/components/typeIt.vue')['default']
  }
}
